name: MyCat
main: dk.zolson427.mycat.MyCat
author: zolson427
version: ${project.version}
api-version: 1.13
load: STARTUP
description: Tamed cats!
depend: []
softdepend: [Vault]
website: https://github.com/zolson427/MyCat
commands:
   mycat:
      description: Command for the MyCat plugin
      usage: /<command> [help]
      aliases: [mc, cat, cats]
permissions:
    mycat.*:
        description: Gives access to all MyCat commands
        default: false
        children:
            mycat.all: true
    mycat.all:
        description: Gives access to all MyCat commands
        default: false
        children:
            mycat.teleport: true
            mycat.reload: true
            mycat.save: true
            mycat.help: true
            mycat.putdown: true
            mycat.cats: true
            mycat.stats: true
            mycat.comehere: true
            mycat.rename: true
            mycat.free: true
            mycat.setid: true
            mycat.editlevel: true
            mycat.dead: true
            mycat.revive: true
            mycat.sit: true
            mycat.togglemode: true
            mycat.pet: true
            mycat.pet.others: true
            mycat.trade: true
    mycat.limit.*:
        description: Give limits to the amount of cats a player can tame.
        default: false
    mycat.teleport:
        description: Player's tamed wolves will teleport to the player
        default: true
    mycat.help:
        description: Player can view the MyCat command list
        default: true
    mycat.putdown:
        description: Player can kill their Cat with a command
        default: true
    mycat.comehere:
        description: Player can force their Cats to load and teleport to the position of the player
        default: true
    mycat.cats:
        description: Player can get an overview about their Cats
        default: true
    mycat.stats:
        description: Player can view stats about their Cats
        default: true
    mycat.rename:
      description: Player can rename their Cats
      default: true
    mycat.sit:
      description: Player can have cats sit and stand up
      default: true
    mycat.setid:
      description: Player can set a custom ID to their Cats
      default: true
    mycat.togglemode:
      description: Player can toggle cats between attack and defend mode
      default: true
    mycat.pet:
      description: Player can pet their cats
      default: true
    mycat.pet.others:
      description: Player can pet others cats
      default: true
    mycat.editlevel:
      description: Player can set the level of their cats
      default: false
    mycat.dead:
      description: Player can see the list of dead cats
      default: true
    mycat.revive:
      description: Player can revive dead cats
      default: true
    mycat.free:
        description: Player can set their Cats free
        default: true
    mycat.trade:
        description: Players can trade their cats
        default: true
    mycat.reload:
        description: Player can reload the configuration(s)
        default: false
    mycat.save:
        description: Player can save the configuration(s)
        default: false       
